- id: jupytext
  name: jupytext
  description: Runs jupytext on all notebooks and paired files.
  language: python
  entry: jupytext --pre-commit-mode
  require_serial: true
  types: [jupyter]
  additional_dependencies:
    - 'nbformat<=5.0.8'
